# Configuration for function minimization example
max_iterations: 20
checkpoint_interval: 1
log_level: "INFO"

# LLM configuration
llm:
  models:
    # - name: "deepseek/deepseek-r1:free"
    - name: "mistral-small-latest"
      weight: 0.8
      # api_base: "https://openrouter.ai/api/v1"
      api_base: "https://api.mistral.ai/v1/"
      temperature: 0.7
      top_p: 0.95
      max_tokens: 4096

    - name: "mistral-large-latest"
      weight: 0.2
      # api_base: "https://openrouter.ai/api/v1"
      api_base: "https://api.mistral.ai/v1/"
      temperature: 0.2
      top_p: 0.95
      max_tokens: 4096

# Prompt configuration
prompt:
  system_message: |
    You are an expert in parametric 3D modeling using CadQuery and Python. Your task is to write a Python function using the CadQuery library that generates a 3D model matching a reference information about the shape as closely as possible.

    Requirements:
    1. The code must use CadQuery primitives and operations.
    2. The function should return final CadQuery solid object (`cq.Workplane` with 3D geometry).
    3. The script must be executable in a standard Python environment with CadQuery installed (no other packages).

    You have a text shape description with important information.

    Here are description of metrics on which
    the result will be evaluated (with respect to original object):
    - "iou": Intersection over Union (perfect match: 1.0)
    - "viou": Inverse Chamfer Distance (perfect match: 1.0)
    - "cd": Inverse Chamfer Distance (perfect match: 1.0)
    - "cdv": Inverse Chamfer Distance on Vertices (perfect match: 1.0)
    - "hd": Inverse Hausdorf Distance (perfect match: 1.0)
    - "hdv": Inverse Hausdorf Distance on Vertices (perfect match: 1.0)
    - "wd": Inverse Wasserstain Distance (perfect match: 1.0)
    - "vs": Volume Similarity (perfect match: 1.0)
    - "as": Surface Area Similarity (perfect match: 1.0)
    - "ctd": Inverse Centroid Distance (perfect match: 1.0)
    - "is": Moment Intertia Simularity (perfect match: 1.0)


    Note: before evaluation the object will be scaled to fit into a 1x1x1 cube, so as the original object will).

    Shape description:
    A 80x60x10 block (length x width x height) with central hole of radius 22

  num_top_programs: 3
  use_template_stochasticity: true

# Database configuration
database:
  population_size: 50
  archive_size: 20
  num_islands: 3
  elite_selection_ratio: 0.2
  exploitation_ratio: 0.7

# Evaluator configuration
evaluator:
  timeout: 120
  use_llm_feedback: false

# Evolution settings
diff_based_evolution: true
allow_full_rewrites: false
